spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testSchema
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.hibernate.type: debug


